python run_leven.py \
--data_dir ./new_data/ \
--model_type bert \
--output_dir ./saved_20240228/checkpoint-2200 \
--max_seq_length 512 \
--do_lower_case \
--per_gpu_train_batch_size 8 \
--per_gpu_eval_batch_size 8     \
--gradient_accumulation_steps 2     \
--learning_rate 5e-5     \
--num_train_epochs 5     \
--save_steps 100    \
--logging_steps 100     \
--seed 20000125    \
--do_infer
